Fix JNumber Deserialize
neo-project/neo pull request #2883
Opened 2023-08-03 02:26 UTC by Ashuaidehao

Close https://github.com/neo-project/neo/issues/2879

2023-08-03 02:53 UTC, Liaojinghui approved these changes

2023-08-03 02:54 UTC, Liaojinghui commented
May you also add a unit test for that

2023-08-03 08:52 UTC, Liaojinghui approved these changes

2023-08-03 12:47 UTC, AnnaShaleva approved these changes

2023-08-03 12:47 UTC, AnnaShaleva commented on src/Neo/SmartContract/JsonSerializer.cs
> +                        return BigInteger.Parse(num.Value.ToString(), System.Globalization.NumberStyles.Float);
That should be enough to fit integers that are allowed by our 256-bit VM. I've checked this fix against the neo-go node, and now both nodes are able to handle big numbers correctly.

2023-08-03 12:47 UTC, AnnaShaleva commented on src/Neo/SmartContract/JsonSerializer.cs
>                          if ((num.Value % 1) != 0) throw new FormatException("Decimal value is not allowed");
And BTW, this line saves us from things like `100.123e+2`. The exception is thrown on attempt to parse it, thus, the second problem described in #2879 isn't relevant:
```
Error Message:
   Test method Neo.UnitTests.SmartContract.UT_JsonSerializer.Deserialize_Array_Bool_Str_Num threw exception: 
System.FormatException: Decimal value is not allowed
  Stack Trace:
      at Neo.SmartContract.JsonSerializer.Deserialize(JToken json, UInt32& maxStackSize, ReferenceCounter referenceCounter) in /home/anna/Documents/GitProjects/neo-project/neo/src/Neo/SmartContract/JsonSerializer.cs:line 193
   at Neo.SmartContract.JsonSerializer.Deserialize(JToken json, UInt32& maxStackSize, ReferenceCounter referenceCounter) in /home/anna/Documents/GitProjects/neo-project/neo/src/Neo/SmartContract/JsonSerializer.cs:line 184
   at Neo.SmartContract.JsonSerializer.Deserialize(JToken json, ExecutionEngineLimits limits, ReferenceCounter referenceCounter) in /home/anna/Documents/GitProjects/neo-project/neo/src/Neo/SmartContract/JsonSerializer.cs:line 168
   at Neo.UnitTests.SmartContract.UT_JsonSerializer.Deserialize_Array_Bool_Str_Num() in /home/anna/Documents/GitProjects/neo-project/neo/tests/Neo.UnitTests/SmartContract/UT_JsonSerializer.cs:line 290
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

2023-08-04 07:08 UTC, superboyiii commented
> @superboyiii Do you think a test for consistancy is necessary?

We can use Basilisk

2023-08-04 09:19 UTC, roman-khimov commented
4c9e33b29bb75ae2a77e180f82879195fe541afa04aabe0e4a1a1ec858629938. We don't have any doing 1.2345e+3, but the possibility of this being unnoticed with 3.5 makes me suggest that Basilisk is the right HF for this change.

2023-08-07 02:53 UTC, superboyiii commented
> 4c9e33b29bb75ae2a77e180f82879195fe541afa04aabe0e4a1a1ec858629938. We don't have any doing 1.2345e+3, but the possibility of this being unnoticed with 3.5 makes me suggest that Basilisk is the right HF for this change.

Yes, let's use Basilisk @Ashuaidehao

2023-08-08 06:26 UTC, shargon requested changes

2023-08-08 06:26 UTC, shargon commented on src/Neo/SmartContract/JsonSerializer.cs
> +                        return BigInteger.Parse(num.Value.ToString(), System.Globalization.NumberStyles.Float);
```suggestion
                        return BigInteger.Parse(num.Value.ToString(CultureInfo.InvariantCulture), NumberStyles.Float);
```

2023-08-09 08:24 UTC, shargon commented
Ready for test @superboyiii

2023-08-10 09:22 UTC, AnnaShaleva approved these changes

2023-08-10 10:16 UTC, Liaojinghui approved these changes

2023-08-11 05:30 UTC, superboyiii commented
> Ready for test @superboyiii

Work as the expected! All data are compatible either on mainnet or  testnet if add a future hard fork.

2023-08-11 05:31 UTC, superboyiii approved these changes

2023-08-14 09:28 UTC, superboyiii commented
```
 public static object Print1(string json)
        {
            //input json = "[200.500000E+005,200.500000e+5,1.1234e+10,9.05E+29]";
            var parsed = StdLib.JsonDeserialize(json);
            return parsed;
        }
```
Input: `"[200.500000E+005,200.500000e+5,1.1234e+10,9.05E+29]"`
Result:
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "DDNbMjAwLjUwMDAwMEUrMDA1LDIwMC41MDAwMDBlKzUsMS4xMjM0ZSsxMCw5LjA1RSsyOV0RwB8MBnByaW50MQwURp5xWNKpMah1VXMjSI/rtnNdtX5BYn1bUg==",
        "state": "HALT",
        "gasconsumed": "3646350",
        "exception": null,
        "notifications": [],
        "stack": [
            {
                "type": "Array",
                "value": [
                    {
                        "type": "Integer",
                        "value": "20050000"
                    },
                    {
                        "type": "Integer",
                        "value": "20050000"
                    },
                    {
                        "type": "Integer",
                        "value": "11234000000"
                    },
                    {
                        "type": "Integer",
                        "value": "905000000000000044735708266496"
                    }
                ]
            }
        ]
    }
}
```
value[3] comparing between this PR and previous one:
![635658ccbcf8fe5a6762c30bc3ef122](https://github.com/neo-project/neo/assets/38493437/aaf559a2-d780-4c47-bd8c-88eeda911625)
Works as expected.

2023-08-15 02:56 UTC, superboyiii commented
@shargon @Liaojinghui merge?

2023-08-15 04:36 UTC, Liaojinghui commented
LGTM

2023-08-15 11:33 UTC, merged