fix trusts conflicts
neo-project/neo pull request #2892
Opened 2023-08-29 16:22 UTC by Liaojinghui

Fix https://github.com/neo-project/neo/issues/2890

2023-08-29 19:45 UTC, roman-khimov requested changes
Thanks for an attempt though, this should be fixed one way or another before 3.6.

2023-08-29 19:45 UTC, roman-khimov commented on src/Neo/SmartContract/Manifest/ContractManifest.cs
> +                Array array when array.Any(p => ((ByteString)p).Size == 0) => WildcardContainer<ContractPermissionDescriptor>.CreateWildcard(),
This seems to be a wrong fix to me. Just store a proper `Null` and read it, similar to permissions.

2023-08-30 05:41 UTC, Liaojinghui commented
should we keep the logic of "of any of the permission is wildcard, then the trust is wildcard"

2023-08-31 13:29 UTC, shargon submitted a review, later dismissed

2023-08-31 14:34 UTC, AnnaShaleva approved these changes
Let's add the https://github.com/Liaojinghui/neo/pull/1 test, please.

LGTM.

2023-09-01 07:58 UTC, Liaojinghui commented
@superboyiii Good to review and merge.

2023-09-01 09:03 UTC, shargon approved these changes

2023-09-01 09:04 UTC, shargon commented
Wait for @superboyiii test

2023-09-01 09:44 UTC, superboyiii commented
I'm resyncing full data on testnet with this implemented, result will come out soon.

2023-09-01 11:03 UTC, superboyiii approved these changes
Tested OK on my privatenet

2023-09-01 11:22 UTC, merged