3.6.0
neo-project/neo pull request #2893
Opened 2023-09-04 12:39 UTC by superboyiii

2023-09-04 12:49 UTC, Liaojinghui submitted a review, later dismissed

2023-09-05 05:15 UTC, erikzhang submitted a review, later dismissed

2023-09-05 05:20 UTC, erikzhang requested changes
You forgot to update the version. It's in the file `Directory.Build.props`.

2023-09-05 05:35 UTC, erikzhang approved these changes

2023-09-05 05:36 UTC, merged