[VM UT] update UT name
neo-project/neo pull request #3115
Opened 2024-02-04 13:54 UTC by Jim8y

# Description

This pr focus on standardize the UT file name and method name.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Just run the existing unit tests

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-05 02:33 UTC, superboyiii commented on tests/Neo.VM.Tests/UT_StackItem.cs
> +        public void TestHashCodeTest()
```suggestion
        public void TestHashCode()
```

2024-02-05 02:33 UTC, superboyiii commented on tests/Neo.VM.Tests/UT_StackItem.cs
> +        public void TestNullTest()
```suggestion
        public void TestNull()
```

2024-02-05 02:34 UTC, superboyiii commented on tests/Neo.VM.Tests/UT_StackItem.cs
> +        public void TestEqualTest()
```suggestion
        public void TestEqual()
```

2024-02-05 02:34 UTC, superboyiii commented on tests/Neo.VM.Tests/UT_StackItem.cs
> +        public void TestCastTest()
```suggestion
        public void TestCast()
```

2024-02-05 02:34 UTC, superboyiii commented on tests/Neo.VM.Tests/UT_StackItem.cs
> +        public void TestDeepCopyTest()
```suggestion
        public void TestDeepCopy()
```

2024-02-05 08:10 UTC, cschuchardt88 requested changes

2024-02-05 08:10 UTC, cschuchardt88 commented on tests/Neo.VM.Tests/UT_ExecutionContext.cs
> +    public class UT__ExecutionContext
```suggestion
    public class UT_ExecutionContext
```

2024-02-05 08:48 UTC, shargon commented on tests/Neo.VM.Tests/UT_ScriptBuilder.cs
> +    public class UT__ScriptBuilder
```suggestion
    public class UT_ScriptBuilder
```

2024-02-05 08:49 UTC, shargon commented on tests/Neo.VM.Tests/UT_EvaluationStack.cs
> +    public class TestEvaluationStack
```suggestion
    public class UT_EvaluationStack
```

2024-02-05 08:51 UTC, shargon submitted a review, later dismissed
LGTM

2024-02-05 09:59 UTC, Jim8y commented
@cschuchardt88

2024-02-05 10:27 UTC, cschuchardt88 approved these changes

2024-02-05 11:47 UTC, shargon commented
Wait for merge to https://github.com/neo-project/neo/pull/3082 or it will produce conflicts

2024-02-07 09:55 UTC, shargon commented
@Jim8y Conflicts

2024-02-07 10:49 UTC, Jim8y commented
@shargon  good to go

2024-02-07 10:54 UTC, shargon approved these changes

2024-02-07 10:54 UTC, merged