SmartContract: catch exception on multisignature contract parsing
neo-project/neo pull request #3211
Opened 2024-05-04 19:05 UTC by AnnaShaleva

# Description

IsMultiSigContract should return proper true/false result even if some garbage is provided as an input. Without this commit an exception is possible during IsMultiSigContract execution during subsequent public key decoding from compressed form:
```
  Failed TestIsMultiSigContract [16 ms]
  Error Message:
   Test method Neo.UnitTests.SmartContract.UT_Helper.TestIsMultiSigContract threw exception:
System.FormatException: Invalid point encoding 221
  Stack Trace:
      at Neo.Cryptography.ECC.ECPoint.DecodePoint(ReadOnlySpan`1 encoded, ECCurve curve) in /home/anna/Documents/GitProjects/neo-project/neo/src/Neo/Cryptography/ECC/ECPoint.cs:line 98
   at Neo.SmartContract.Helper.IsMultiSigContract(ReadOnlySpan`1 script, Int32& m, Int32& n, List`1 points) in /home/anna/Documents/GitProjects/neo-project/neo/src/Neo/SmartContract/Helper.cs:line 189
   at Neo.SmartContract.Helper.IsMultiSigContract(ReadOnlySpan`1 script) in /home/anna/Documents/GitProjects/neo-project/neo/src/Neo/SmartContract/Helper.cs:line 123
   at Neo.UnitTests.SmartContract.UT_Helper.TestIsMultiSigContract() in /home/anna/Documents/GitProjects/neo-project/neo/tests/Neo.UnitTests/SmartContract/UT_Helper.cs:line 65
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Note that this change is **compatible** wrt the callers' behaviour. We need this change to properly handle non-Secp256r1-based witness scripts, ref. https://github.com/neo-project/neo/pull/3209.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] Unit test `TestIsMultiSigContract_WrongCurve`
- [ ] Unit test `TestIsSignatureContract_WrongCurve`

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-05-04 19:16 UTC, vncoelho reviewed
I think it is not "(non-breaking change which fixes an issue)", @AnnaShaleva .

Perhaps that without a proper version control an attacker could try to use this function and change behavior of past executions.
But I did not test yet.

2024-05-04 19:24 UTC, cschuchardt88 requested changes
Please write test for `IVerifable.VerifyStateIndependent` and `IVeriable.VerifyWitnesses` just to make sure they work with changes.

https://github.com/neo-project/neo/blob/429a081753e46d995829c5182a3f73bc55a63741/src/Neo/Network/P2P/Payloads/Transaction.cs#L432

https://github.com/neo-project/neo/blob/429a081753e46d995829c5182a3f73bc55a63741/src/Neo/SmartContract/Helper.cs#L283

2024-05-04 19:27 UTC, vncoelho reviewed
@AnnaShaleva,

I double checked here,
perhaps it does not need version control. In fact, it looks like it is just internal for fee calculations and transaction creation. Thus, it would not affect the understanding of previous transactions.

2024-05-04 19:58 UTC, roman-khimov approved these changes
Correct fix (and likely more important than just to "properly handle non-Secp256r1-based witness scripts"), but I fear we may have more cases like this in the codebase (like VerifySignature).

2024-05-04 20:09 UTC, cschuchardt88 commented
@roman-khimov 
> Correct fix (and likely more important than just to "properly handle non-Secp256r1-based witness scripts"), but I fear we may have more cases like this in the codebase (like VerifySignature).

Hints my tests for `IVerifable.VerifyStateIndependent` if it errors it should return `VerifyResult.Succeed`.

https://github.com/neo-project/neo/pull/3211#pullrequestreview-2039531736

2024-05-04 20:44 UTC, AnnaShaleva commented
I've tested the current node version in neo-bench. Without this fix anyone can kill the node for free by sending transaction with a special witness that contains improperly encoded public key:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-bench$ make start.SharpFourNodes25rate 
./runner.sh --nodes sharp --rpc sharp -d "Sharp4x_SharpRPC" -m rate -q 25 -z 5m -t 30s -l
make[1]: Entering directory '/home/anna/Documents/GitProjects/nspcc-dev/neo-bench'
=> Stop environment
=> Generate configurations for single-node and four-nodes networks from templates
+ cd ./cmd
+ go run ./config/ --go-template go.protocol.template.yml --go-db leveldb --sharp-template sharp.protocol.template.yml --sharp-db LevelDBStore --msPerBlock 0
creating: 214637147/go.protocol.template.yml
creating: 214637147/go.protocol.template.yml
creating: 214637147/sharp.protocol.template.yml
creating: 214637147/sharp.protocol.template.yml
make[1]: Leaving directory '/home/anna/Documents/GitProjects/nspcc-dev/neo-bench'
[+] Creating 8/5
 ✔ Network neo_go_network        Created                                                                                                                                                                      0.0s 
 ✔ Container neo-cli-node-one    Created                                                                                                                                                                      0.1s 
 ✔ Container neo-cli-node-three  Created                                                                                                                                                                      0.1s 
 ✔ Container neo-cli-node-four   Created                                                                                                                                                                      0.1s 
 ✔ Container neo-cli-node-two    Created                                                                                                                                                                      0.1s 
 ✔ Container ir-healthy-1        Created                                                                                                                                                                      0.0s 
 ✔ Container sharp-node          Created                                                                                                                                                                      0.0s 
 ✔ Container ir-node_healthy-1   Created                                                                                                                                                                      0.0s 
[+] Running 7/7
 ✔ Container neo-cli-node-four   Healthy                                                                                                                                                                      6.0s 
 ✔ Container neo-cli-node-one    Healthy                                                                                                                                                                      6.0s 
 ✔ Container neo-cli-node-two    Healthy                                                                                                                                                                      6.0s 
 ✔ Container neo-cli-node-three  Healthy                                                                                                                                                                      6.0s 
 ✔ Container ir-healthy-1        Started                                                                                                                                                                      0.3s 
 ✔ Container sharp-node          Healthy                                                                                                                                                                      5.8s 
 ✔ Container ir-node_healthy-1   Started                                                                                                                                                                      0.3s 
2024/05/04 20:38:41 Used [sharp-node:20331] rpc addresses
2024/05/04 20:38:41 Run benchmark for Sharp4x_SharpRPC :: Neo_3.6.2
2024/05/04 20:38:50 Read 3000000 txs from /dump.txs
2024/05/04 20:38:56 Done 6.188798538s
2024/05/04 20:38:56 Init worker with 25 QPS / 5m0s time limit (3000000 txs will try to send)
2024/05/04 20:38:56 Prepare chain for benchmark
2024/05/04 20:38:56 Determined validators count: 4
2024/05/04 20:38:56 Sending NEO and GAS transfer tx
2024/05/04 20:39:00 CPU: 5.109%, Mem: 831.543MB
2024/05/04 20:39:01 Sending bad tx
2024/05/04 20:39:05 could not create blocks: could not send prepare tx: Post "http://sharp-node:20331": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
make: *** [Makefile:233: start.SharpFourNodes25rate] Error 1
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-bench$ docker logs sharp-node 
NEO-CLI v3.6.2  -  NEO v3.6.2  -  NEO-VM v3.6.2

neo> ERROR [20:39:01.053] 	Invalid point compression
```

So @roman-khimov is right about the fact that this issue is quite severe. If needed, I may attach the transaction generation code.

2024-05-04 21:05 UTC, shargon approved these changes

2024-05-04 21:21 UTC, vncoelho approved these changes

2024-05-05 03:37 UTC, Jim8y approved these changes

2024-05-05 10:06 UTC, merged