COVERALL: Improve maintenance and readbility of some variables
neo-project/neo pull request #3248
Opened 2024-05-21 10:38 UTC by vncoelho

2024-05-21 11:16 UTC, Jim8y commented
LGTM

2024-05-21 11:16 UTC, Jim8y submitted a review, later dismissed

2024-05-21 11:36 UTC, shargon commented
still not working

2024-05-21 11:37 UTC, shargon reviewed
I prefer to fix the issue instead of change the style (or both together)

2024-05-21 11:38 UTC, vncoelho commented
> I prefer to fix the issue instead of change the style (or both together)

You can try the fix in another PR.
I still did not figure out the fix.

2024-05-21 11:43 UTC, Jim8y commented
> I think there is some error introduced @Jim8y
> 
> ```shell
> [coverlet] MergeWith: file ''/home/runner/work/neo/neo/TestResults/coverage/coverage.json'' does not exist.
>    Generating report '/home/runner/work/neo/neo/tests/Neo.Plugins.Storage.Tests/'/home/runner/work/neo/neo/TestResults/coverage/'.info'
> ```
> 
> I just checked here on the report. Let me try to fix.

I compared the string,,,,, they are the same.... not sure whats wrong

2024-05-21 11:44 UTC, shargon requested changes
maybe we need different arguments in different calls, I think that this pr is not required, we need to solve the coverage issue, after it, maybe this change is not required.

2024-05-21 11:51 UTC, vncoelho commented
> maybe we need different arguments in different calls, I think that this pr is not required, we need to solve the coverage issue first, after it, maybe this change is not required.

After the fix I will open this again

2024-05-21 11:51 UTC, vncoelho commented
> > maybe we need different arguments in different calls, I think that this pr is not required, we need to solve the coverage issue first, after it, maybe this change is not required.
> 
> After the fix I will redo this again

2024-05-22 02:06 UTC, cschuchardt88 requested changes

2024-05-22 02:06 UTC, cschuchardt88 commented on .github/workflows/main.yml
> +        COVERALL_COLLECT_OUTPUT="/p:CollectCoverage=true /p:CoverletOutput='${{ github.workspace }}/TestResults/coverage/'"
Can you please use `github` environment to do this. Its easier to maintain and read/debug.

2024-05-22 10:05 UTC, vncoelho commented
@cschuchardt88, sure! I will try with git-env.

I will reopen after the fix.

2024-05-22 20:37 UTC, shargon approved these changes

2024-05-23 00:26 UTC, Jim8y approved these changes

2024-05-23 02:09 UTC, cschuchardt88 approved these changes

2024-05-23 08:31 UTC, merged