[Neo Plugin New feature] Stop plugins on Unhandled Exception
neo-project/neo pull request #3311
Opened 2024-06-09 10:42 UTC by Jim8y

# Description

This is a follow up work after https://github.com/neo-project/neo/pull/3309. This pr will stop a plugin if a plugin throws an unhandled exception, but we also allow user to specify plugins not to stop on exception (except store plugins.).

Fixes # follow https://github.com/neo-project/neo/pull/3309

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] TestOnPluginStopOnException
- [x] TestOnPluginStopped

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-09 21:14 UTC, cschuchardt88 submitted a review, later dismissed

2024-06-10 08:17 UTC, shargon commented on src/Neo/Plugins/PluginSettings.cs
> +                return policy;
```suggestion
                return policy;
```

2024-06-10 08:17 UTC, shargon commented on src/Neo/Ledger/Blockchain.cs
> +
```suggestion

```

2024-06-10 08:19 UTC, shargon commented on src/Neo/Plugins/PluginSettings.cs
> +            var policyString = section.GetValue("UnhandledExceptionPolicy", "StopNode");
```suggestion
            var policyString = section.GetValue("UnhandledExceptionPolicy", nameof(UnhandledExceptionPolicy.StopNode));
```

2024-06-11 03:05 UTC, cschuchardt88 requested changes

2024-06-11 03:05 UTC, cschuchardt88 commented on src/Neo/Plugins/PluginSettings.cs
> +            var policyString = section.GetValue("UnhandledExceptionPolicy", nameof(UnhandledExceptionPolicy.StopNode));
```suggestion
            var policyString = section.GetValue(nameof(UnhandledExceptionPolicy), nameof(UnhandledExceptionPolicy.StopNode));
```

2024-06-11 03:05 UTC, cschuchardt88 commented on src/Plugins/TokensTracker/TokensTracker.cs
> +            var policyString = config.GetValue("UnhandledExceptionPolicy", "StopNode");
```suggestion
            var policyString = config.GetValue(nameof(UnhandledExceptionPolicy), nameof(UnhandledExceptionPolicy.StopNode));
```

2024-06-11 10:29 UTC, shargon commented on src/Neo/Plugins/PluginSettings.cs
> +            var policyString = section.GetValue("UnhandledExceptionPolicy", "StopNode");
there are more

2024-06-16 15:27 UTC, cschuchardt88 approved these changes

2024-06-17 07:36 UTC, superboyiii commented
Maybe TokenTracker should be the same default settings as Applicationlogs.

2024-06-17 10:46 UTC, Jim8y commented
> Maybe TokenTracker should be the same default settings as Applicationlogs, they're working in similar behaviours.

will update.

2024-06-18 01:52 UTC, Jim8y commented on src/Plugins/TokensTracker/TokensTracker.json
> +    "UnhandledExceptionPolicy": "Ignore"
```suggestion
    "UnhandledExceptionPolicy": "StopPlugin"
```

2024-06-18 03:58 UTC, cschuchardt88 approved these changes

2024-06-18 07:55 UTC, Jim8y commented
Following the call of the TC, this pr will be halted for 3-6 months. Thus please don't merge this pr.

2024-06-18 10:26 UTC, shargon commented
> Following the call of the TC, this pr will be halted for 3-6 months. Thus please don't merge this pr.

This is required if we merged the previous related one

2024-06-18 15:12 UTC, Jim8y commented
> > Following the call of the TC, this pr will be halted for 3-6 months. Thus please don't merge this pr.
> 
> This is required if we merged the previous related one. I Didn't read it nothing related against this pr
> 
> https://github.com/neo-project/neo/pull/3309#pullrequestreview-2121384853

sure. since coredev meeting is scheduled next week, i think it should still be fine to merge this one.

2024-06-18 15:12 UTC, merged

2024-06-18 15:12 UTC, Jim8y commented
@shargon can you please merge this branch to master?

2024-06-18 15:14 UTC, vncoelho commented
@Jim8y 

Try https://github.com/neo-project/neo/compare/plugin-unhandled-exception?expand=1