[rpc] Extend `getversion` RPC response with additional protocol settings
neo-project/neo pull request #3443
Opened 2024-07-29 16:21 UTC by shargon

# Description

Fix https://github.com/neo-project/neo/issues/3401

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] UT_RpcServer.TestGetVersion

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-29 16:50 UTC, cschuchardt88 approved these changes

2024-07-29 16:51 UTC, roman-khimov reviewed
Don't we need to extend the RPC client as well?

2024-07-30 03:31 UTC, Jim8y commented
@chenzhitong please update the document accordingly.

2024-07-30 03:32 UTC, Jim8y submitted a review, later dismissed

2024-07-30 06:15 UTC, NGDAdmin requested changes
@shargon Please update RpcClient as well.

2024-07-30 08:40 UTC, NGDAdmin approved these changes

2024-07-30 09:42 UTC, Jim8y approved these changes

2024-07-30 17:29 UTC, merged