3s consensus - With consensus time included into consensus intervals.
neo-project/neo pull request #3622
Opened 2024-12-12 15:01 UTC by Jim8y

# Description

Credits of this pr belong to @AnnaShaleva. Changes included into this PR:
1. Move MSPerBlock protocol configuration to native Policy contract.
2. Take into account PrepareRequest receival time during dBFT timer reset (close #3627).

## Type of change

- [X] Enhancement.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-12-12 15:03 UTC, Jim8y commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
This is the major change to this pr

2025-02-11 07:45 UTC, Jim8y commented on src/Neo/SmartContract/Native/NeoToken.cs
> +        public BigInteger GetGasPerBlock(ApplicationEngine engine, DataCache snapshot)
@shargon @roman-khimov please check this, i am try to update the gasperblock without really update it casue it should be a council thing.

2025-02-11 11:22 UTC, shargon commented on src/Neo/SmartContract/Native/NeoToken.cs
> +        public BigInteger GetGasPerBlock(ApplicationEngine engine, DataCache snapshot)
You can change the arguments without hardfork, because both arguments are native ones

2025-02-11 11:22 UTC, shargon commented on src/Neo/SmartContract/Native/NeoToken.cs
> +        public BigInteger GetGasPerBlock(ApplicationEngine engine, DataCache snapshot)
But we should not write into storages here... should be done by council

2025-02-11 11:23 UTC, shargon commented on src/Neo/SmartContract/Native/NeoToken.cs
> +        public BigInteger GetGasPerBlock(ApplicationEngine engine, DataCache snapshot)
Maybe CN can detect when this is made by council and start the new time?

2025-02-11 12:57 UTC, Jim8y commented on src/Neo/SmartContract/Native/NeoToken.cs
> +        public BigInteger GetGasPerBlock(ApplicationEngine engine, DataCache snapshot)
Hi shargon, i think my latest commit has addressed your concern:

1. reuse existing GetGasPerBlock
2. avoid write to the store but directly calculate a value
3. ensures the council can still update the gasperblock, and the new value can be used immediately.

2025-02-11 12:59 UTC, Jim8y commented on src/Neo/SmartContract/Native/NeoToken.cs
> +        public BigInteger GetGasPerBlock(ApplicationEngine engine, DataCache snapshot)
I intentially have two return currentgasperblolck to make the logic more clear as they are different situations. Code can be optimized if the logic passes review if necessary.

2025-02-11 13:27 UTC, roman-khimov requested changes
1. Most of the changes in this PR are just not needed at all (the only relevant is timer shift in fact).
2. No hardfork is needed to change the block time in the current structure. It's just a matter of restarting consensus nodes with appropriate configuration.
3. No native contract changes are required to change the GAS per block value. It's just a matter of sending a committee transaction. This one is really serious, btw, we do have a governance model and your changes just break it.
4. Give 2 and 3 we can just schedule 3s block time to some post-Echidna date, create and send a transaction, restart CNs. This won't and can't be perfectly aligned, true, but I doubt it's a problem in practice. Changing governance assumptions behind the scenes is much bigger problem.
5. But this still doesn't answer the time lock problem we can have with mainnet.

2025-02-11 13:27 UTC, roman-khimov commented on src/Neo/ProtocolSettings.cs
> +            MaxTransactionsPerBlock = 256,
Why changing the default here? Why changing it at all? It doesn't matter how many transactions we have, execution resources are controlled with GAS.

2025-02-11 13:27 UTC, roman-khimov commented on src/Neo/SmartContract/Native/NeoToken.cs
> +                // After HARD FORK
Please do not do this at all.

2025-02-11 13:27 UTC, roman-khimov commented on src/Neo/SmartContract/Native/NeoToken.cs
> +            currentGasPerBlock /= 5; // I think it should not be a problem for this code to ensure the result is not 0
NACK. This MUST NOT be done at the code level. We have committee to do this and different networks can legitimately have very different settings.

2025-02-11 13:35 UTC, Jim8y commented on src/Neo/SmartContract/Native/NeoToken.cs
> +            currentGasPerBlock /= 5; // I think it should not be a problem for this code to ensure the result is not 0
Sure, you and shargon share the same idea, if you think gasperblock should be a pure council thing, i have no problem with that at all, lets discuss it in the meeting.

2025-02-11 13:36 UTC, Jim8y commented on src/Neo/ProtocolSettings.cs
> +            MaxTransactionsPerBlock = 256,
This is from vitor's previous PR, lets decides it during the meeting.

2025-02-11 13:38 UTC, Jim8y commented on src/Neo/ProtocolSettings.cs
> +            MaxTransactionsPerBlock = 256,
May I ask what is `the time lock problem`? the last time i heard time lock is from hash time lock contract on lighting network.

2025-02-11 13:43 UTC, Jim8y commented on docs/config.json.md
> +- **MaxTransactionsPerBlock**: Maximum number of transactions allowed per block. Default is `256`.
```suggestion
- **MaxTransactionsPerBlock**: Maximum number of transactions allowed per block. Default is `512`.
```

2025-02-11 13:44 UTC, Jim8y commented on src/Neo.CLI/config.testnet.json
> +    "MaxTransactionsPerBlock": 512,
```suggestion
    "MaxTransactionsPerBlock": 5000,
```

2025-02-11 13:44 UTC, Jim8y commented on tests/Neo.Plugins.OracleService.Tests/config.json
> +    "MaxTransactionsPerBlock": 256,
```suggestion
    "MaxTransactionsPerBlock": 512,
```

2025-02-11 13:45 UTC, Jim8y commented on src/Neo/ProtocolSettings.cs
> +            MaxTransactionsPerBlock = 256,
Now latest version only keeps the change to the block time.

2025-02-11 14:15 UTC, roman-khimov commented on src/Neo/ProtocolSettings.cs
> +            MaxTransactionsPerBlock = 256,
> May I ask what is the time lock problem?

Consider a contract that wants to lock some assets for some period of time, like a year. Developers know that blocks are ~15s and blocks are very convenient to count, so they can easily put a lock to expire at "current block + 2102400". And it's all fine except we're breaking this basic assumption of 15s and suddenly this lock expires somewhat earlier. Whether it's a problem or not for any real N3 mainnet contract is unknown, but it can be.

2025-02-11 20:13 UTC, shargon commented on src/Neo/SmartContract/Native/NeoToken.cs
> +            currentGasPerBlock /= 5; // I think it should not be a problem for this code to ensure the result is not 0
We can avoid the reward if is higer than X, this will push committee to do the change

2025-02-12 01:13 UTC, vncoelho commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
This should be in another PR and not here, if that is the case.

And for your notice, as I said in our meetings, this configuration has been tested in the past.

I think that you need more experimental tests before publishing things to quick and even writing new standards (that are not even necessary). 
I am not saying that the change is terrible, @Jim8y, but there are some consequences, I think that you did not analyse the entire scenario before pushing this and creating standards with it.

I will surely be against this change here in this PR for a series of reasons.
Try this in a decentralized scenario or inserting delays (you can deal with that on docker) or create on AWS/AZURE in different locations.

2025-02-12 01:14 UTC, vncoelho requested changes
There are changes not necessary for this PR.
Some of them were extensive explored in the past with strong experiments. Thus, for their current implementation REAL tests and a MINIMAL care with running a real scenario is surely necessary.

2025-02-12 01:17 UTC, Jim8y commented on src/Neo/SmartContract/Native/NeoToken.cs
> +            currentGasPerBlock /= 5; // I think it should not be a problem for this code to ensure the result is not 0
according to roman's comment, we should not touch the GAS reward at all, so i assume maybe that allow a few block to have 5 gas minted after the hardfork is acceptable. Lets discuss it in the meeting.

2025-02-12 01:19 UTC, Jim8y commented
> There are changes not necessary for this PR. Some of them were extensive explored in the past with strong experiments. Thus, for their current implementation REAL tests and a MINIMAL care with running a real scenario is surely necessary.

This pr is already being running in real scenario for 2 weeks, stress test included， and of course it will also be tested in the testnet for weeks, but that will be after the merge of this pr.

2025-02-12 01:23 UTC, cschuchardt88 commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
> this configuration has been tested in the past.

Lots have changed in code since then. Would that affect anything like this? if so, we have to run these tests again to ensure its trueful.

2025-02-12 01:30 UTC, vncoelho commented
@Jim8y 
Where is it running and which setup ?

There are some problems with this change when we have change views, and more normally when the multiplied by factor is applied. It also have a cascade effect when a node has delays and did not still processed last commit, but, the one who processed and is the Speaker would already have sent next Prepare Request. 

Maybe other components on Neo Core improved, which is surely true. But in the past we where not able to run this scenario efficiently. I am not saying it is not possible, but my suggestion would surely be to merge these changes apart of the time change, which does not necessary need this in the first moment.

2025-02-12 01:31 UTC, Jim8y commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
> This should be in another PR and not here, if that is the case.
> 
> And for your notice, as I said in our meetings, this configuration has been tested in the past.
> 
> I think that you need more experimental tests before publishing things to quick and even writing new standards (that are not even necessary). I am not saying that the change is terrible, @Jim8y, but there are some consequences, I think that you did not analyse the entire scenario before pushing this and creating standards with it.
> 
> I will surely be against this change here in this PR for a series of reasons. Try this in a decentralized scenario or inserting delays (you can deal with that on docker) or create on AWS/AZURE in different locations.

We have setup a real testnet to carry out stress test and stability test. The network works fine and no issue. As you said should be in another pr thing, all changes in this pr now is for the service of  and only serve the 3-seconds consensus, it is meaningless to add any of the prs and test any of the prs that only contain part of the changes in this pr. Casue non of the code in this pr means a thing without rest part.

We encourage small prs for the intention of easier review and test, its not like everything must be as small as possible.
If there is no review issue and no real logic problem, it is just an unnecessary waste of the time and test resource.

2025-02-12 01:33 UTC, vncoelho commented
I will try to run this in an abnormal scenario and check results.

2025-02-12 01:36 UTC, Jim8y commented
> @Jim8y Where is it running and which setup ?
> 
> There are some problems with this change when we have change views, and more normally when the multiplied by factor is applied. It also have a cascade effect when a node has delays and did not still processed last commit, but, the one who processed and is the Speaker would already have sent next Prepare Request.
> 
> Maybe other components on Neo Core improved, which is surely true. But in the past we where not able to run this scenario efficiently. I am not saying it is not possible, but my suggestion would surely be to merge these changes apart of the time change, which does not necessary need this in the first moment.

Sorry the testnet was setup and run for weeks with all information and result being shared in the core dev chatting group and TC chatting group. While the testnet was running, I encouraged everyone to run tests over the testnet. The testnet was shutted down after running for a few weeks due to high service cost.

2025-02-12 01:39 UTC, vncoelho commented
I remember to see some results, was @superboyiii in charge of the simulation scenario?

2025-02-12 01:40 UTC, vncoelho commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
> Lots have changed in code since then. Would that affect anything like this? if so, we have to run these tests again to ensure its trueful.

You are right @cschuchardt88 , I was also saying that in my last message. Let's see

2025-02-12 01:42 UTC, Jim8y commented
> I remember to see some results, was @superboyiii in charge of the simulation scenario?

Yes, @superboyiii setup a 7 nodes testnet on the cloud servers, for a while when the stress test was running, one of the node is running on my local mac machine. That testnet run for weeks and smothly generate new blocks with 3-seconds consensus. Such test is very expensive,,, so not likely to do it again if there is no changes that can directly affect this pr.

2025-02-12 15:29 UTC, vncoelho commented
Congratulations to the core devs for the general work, the consensus is much more stable as well as the P2P, my last simulation environment surprised myself.

Regarding the PR itself, the changes looks good to me, but some modification are still needed before approval.

2025-02-12 19:29 UTC, shargon commented on src/Neo/ProtocolSettings.cs
> +            MaxTransactionsPerBlock = 256,
Agree, it was recommended to use block number instead of time because time can be controlled by CN, now of we change this rule, contracts can be affected, we should ensure how many contracts use time o block height syscalls

2025-02-19 14:33 UTC, shargon commented on src/Neo/ProtocolSettings.cs
> +        public uint MaxValidUntilBlockIncrement => 86400000 / MillisecondsPerBlock; //TODO keep the same??
Can be different after the HF? (Or related to MsPerBlock)

2025-02-19 14:45 UTC, roman-khimov commented on src/Neo/ProtocolSettings.cs
> +        public uint MaxValidUntilBlockIncrement => 86400000 / MillisecondsPerBlock; //TODO keep the same??
It's safe to make it bigger, won't invalidate any old transactions. The intent was to have a day of blocks. In most scenarios it's an overkill (I specifically prefer short transaction lifetimes, 10 blocks is more than enough), but in some cases it's still relevant, consider manually (hi, #1573) signing a committee transaction.

One caveat is that it can not be more than `MaxTraceableBlocks`, otherwise replays would be possible.

2025-02-19 17:18 UTC, shargon commented on src/Neo/ProtocolSettings.cs
> +        public uint MaxValidUntilBlockIncrement => 86400000 / MillisecondsPerBlock; //TODO keep the same??
But now how many years we will preserve?

2025-02-19 18:33 UTC, roman-khimov commented on src/Neo/ProtocolSettings.cs
> +        public uint MaxValidUntilBlockIncrement => 86400000 / MillisecondsPerBlock; //TODO keep the same??
`MaxTraceableBlocks` is 2102400 irrespective of block time, but I really (_really_) would like it to be lower, as in #3644. With MVUBI of 28800 (as per 3s MillisecondsPerBlock) we can have MTB of 30K. Or we can lower MVUBI to 14400 and have MTB of 20K. Either way it's all per-network, FS networks already use pretty low MTB (and testnet runs at 1s block time) and we love it.

2025-02-19 18:35 UTC, roman-khimov commented on src/Neo/ProtocolSettings.cs
> +        public uint MaxValidUntilBlockIncrement => 86400000 / MillisecondsPerBlock; //TODO keep the same??
Notice also that it's all configurable, we don't need to change anything in the code, just update settings.

2025-02-25 01:46 UTC, cschuchardt88 approved these changes

2025-02-25 13:55 UTC, roman-khimov commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
>          private DateTime block_received_time;
I think this can be dropped now.

2025-02-25 13:55 UTC, roman-khimov commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +            ExtendTimerByFactor(4);
These coefficients is what I'm not so sure about, but if @vncoelho thinks it's better this way I'm not insisting on keeping them as is.

2025-02-25 14:13 UTC, vncoelho commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +            ExtendTimerByFactor(4);
In my tests here they behaved good.
And the adjusts were all empircally calculated with some technical knowledge..ahahha

2025-02-25 14:41 UTC, roman-khimov commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +            ExtendTimerByFactor(4);
Just to mention, https://neospcc.medium.com/under-pressure-time-constrained-dbft-a4b4f30b73fd was done with the original ones. Worked fine as well. But that network had little delays overall, even at 100ms it was noticeably distant from the 25ms inter-DC latency.

2025-02-26 00:33 UTC, vncoelho commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +            ExtendTimerByFactor(4);
I think it is more needed when we have more delays, it is a protection as well. It does need change, at all, the time for the first round decision.
It just would alter round 2.

2025-03-03 17:08 UTC, belane commented
As previously discussed, modifying the blocktime could introduce risks to some projects. Specifically, projects that rely on the assumption of a fixed lock time for time-based calculations (vestings, timelocks, rewards, ...).

For a smart contract to be impacted by this change, it must be aware of the current time in some way. I think this can only happen through one of the following methods (if there are other ways, suggestions are welcome):

- Use `GetTime`.
- Retrieve the current block and extract the block timestamp.
- Retrieve the current block hash, query the block by hash, and extract the timestamp.

A quick search for these patterns reveals some contracts that could be affected by this change. It would be advisable that we contact each project and evaluate the impact on a case-by-case basis.

- [mainnet](https://gist.github.com/belane/0d61a85c6ab85ce1c9e1fa0d88da2874#file-mainnet-csv)
- [testnet](https://gist.github.com/belane/0d61a85c6ab85ce1c9e1fa0d88da2874#file-testnet-csv)

2025-03-04 07:52 UTC, superboyiii commented on src/Neo/ProtocolSettings.cs
> +            MillisecondsPerBlock = 3000,
We should get time from Native.PolicyContract.GetBlockGenTime()

2025-03-04 07:59 UTC, superboyiii commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    TimeSpan blockTime = GetBlockTimeFromPolicyContract();
No, it should get `MillisecondsPerBlock` from neoSystem.Settings before `HF_Domovoi`.

2025-03-04 08:03 UTC, superboyiii commented on src/Plugins/StateService/Verification/VerificationContext.cs
> +        private const uint MaxValidUntilBlockIncrement = 100; // Change to 500!??
It' OK. Don't need change.

2025-03-04 08:09 UTC, superboyiii commented
We should keep all config.json unchanged for `MillisecondsPerBlock`. And after `HF_Echidna`, then all reference about `MillisecondsPerBlock` should be taken place with Native.PolicyContract.GetBlockGenTime().

2025-03-04 08:09 UTC, superboyiii commented on benchmarks/Neo.Benchmarks/config.json
> +    "MillisecondsPerBlock": 3000,
Don't change here.

2025-03-04 08:09 UTC, superboyiii commented on src/Neo.CLI/config.fs.testnet.json
> +    "MillisecondsPerBlock": 3000,
Don't change here.

2025-03-04 08:09 UTC, superboyiii commented on src/Neo.CLI/config.testnet.json
> +    "MillisecondsPerBlock": 3000,
Don't change here.

2025-03-04 08:12 UTC, superboyiii commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.Check.cs
> +                ExtendTimerByFactor(4);
Need dynamic calculation based on Native.PolicyContract.GetBlockGenTime().

2025-03-04 08:13 UTC, superboyiii commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +            ExtendTimerByFactor(4);
Need dynamic calculation based on Native.PolicyContract.GetBlockGenTime().

2025-03-04 08:13 UTC, superboyiii commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +            ExtendTimerByFactor(4);
Need dynamic calculation based on Native.PolicyContract.GetBlockGenTime().

2025-03-04 08:13 UTC, superboyiii commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +                ExtendTimerByFactor(6);
Need dynamic calculation based on Native.PolicyContract.GetBlockGenTime().

2025-03-04 08:14 UTC, superboyiii commented on tests/Neo.Plugins.OracleService.Tests/config.json
> +    "MillisecondsPerBlock": 3000,
Don't change, should be the same behaviour as other config.json

2025-03-04 08:15 UTC, superboyiii commented on tests/Neo.Network.RPC.Tests/RpcTestCases.json
> +          "msperblock": 3000,
Don't change, should be the same behaviour as other config.json

2025-03-04 08:16 UTC, superboyiii commented on tests/Neo.UnitTests/UT_ProtocolSettings.cs
> +            Assert.AreEqual((uint)3000, (uint)TestProtocolSettings.Default.MillisecondsPerBlock);
It's OK to try 150000 because we will not use `MillisecondsPerBlock` from ProtocolSettings anymore.

2025-03-04 08:17 UTC, superboyiii commented on tests/Neo.UnitTests/UT_ProtocolSettings.cs
> +    ""MillisecondsPerBlock"": 3000,
Need revert

2025-03-04 08:17 UTC, superboyiii commented on tests/Neo.UnitTests/test.config.json
> +    "MillisecondsPerBlock": 3000,
Need revert

2025-03-04 08:41 UTC, superboyiii commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        [ContractMethod(CpuFee = 1 << 15, RequiredCallFlags = CallFlags.ReadStates)]
```suggestion
        [ContractMethod(Hardfork.HF_Echidna, CpuFee = 1 << 15, RequiredCallFlags = CallFlags.ReadStates)]
```

2025-03-06 07:46 UTC, superboyiii commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.Check.cs
> +                ExtendTimerByFactor(4);
This is not good. That means can have 4*15s delay for 1 round if not enough PrepareResponse before SetBlockGenTime to 3s. I think keep it as 2 is not bad. We should only change variable but keep coefficient。

2025-03-06 09:15 UTC, shargon commented on tests/Neo.Plugins.OracleService.Tests/config.json
> +    "MillisecondsPerBlock": 3000,
```suggestion
    "MillisecondsPerBlock": 15000,
```

2025-03-06 09:18 UTC, shargon commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                if (!system.Settings.IsHardforkEnabled(Hardfork.HF_Echidna, index - 1))
why -1?

2025-03-07 09:53 UTC, superboyiii commented on docs/config.json.md
> +- **HF_Domovoi**: Block height for the Domovoi hard fork.
```suggestion
- **HF_Domovoi**: Block height for the Domovoi hard fork. MainNet is `5570000`, TestNet is `4144000`.
```

2025-03-07 09:58 UTC, superboyiii commented on src/Neo/ProtocolSettings.cs
> +        public uint MaxValidUntilBlockIncrement => 86400000 / MillisecondsPerBlock; //TODO keep the same??
```suggestion
        public uint MaxValidUntilBlockIncrement => 86400000 / MillisecondsPerBlock;
```
It's OK, it's still timestamp for 24 hrs.

2025-03-07 10:27 UTC, superboyiii commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            if (milliseconds < MinBlockGenTime) throw new ArgumentOutOfRangeException(nameof(milliseconds));
```suggestion
            if (milliseconds < MinBlockGenTime) throw new ArgumentOutOfRangeException(nameof(milliseconds), $"Block generation time cannot be less than {MinBlockGenTime} milliseconds");
```

2025-03-07 10:38 UTC, roman-khimov commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 1000;
At least 100. N3 is more than two networks, committee should be able to run faster networks if/when needed.

2025-03-07 10:38 UTC, roman-khimov commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(DefaultBlockGenTime));
Not appropriate. FS networks are already faster than this. We also need to be able to specify this value in the genesis configuration, so if it's there the value should be taken from config. Similar to https://github.com/nspcc-dev/neo-go/blob/master/docs/node-configuration.md#Genesis-Configuration

2025-03-07 10:38 UTC, roman-khimov commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 1000;
But better not have any limit at all. We may want 50ms in some scenarios.

2025-03-07 11:16 UTC, shargon commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 1000;
it's better to have a max

2025-03-07 11:56 UTC, AnnaShaleva commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                if (!system.Settings.IsHardforkEnabled(Hardfork.HF_Echidna, index - 1))
Agree, it looks like we need just `index` here, because this block is already persisted by this moment.

2025-03-07 11:56 UTC, AnnaShaleva commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                return TimeSpan.FromMilliseconds(milliseconds);
We can reuse `GetBlockGenTime(this IReadOnlyStore snapshot, ProtocolSettings settings)` extension from this method in order not to duplicate the code. Can't we?

2025-03-07 11:56 UTC, AnnaShaleva commented on src/Neo/Ledger/Blockchain.cs
> +                    ? (ProtocolSettings.Default.MillisecondsPerBlock - (uint)system.GetBlockGenTime().TotalMilliseconds) / 1000
We need to be careful with such changes, it's important. The problem is that `GetBlockGenTime()` now refers to the current block height and the storage. Both height and storage may be upgraded between two subsequent calls to `GetBlockGenTime()`. Hence, I think we need to calulate `GetBlockGenTime()` once, store result in a variable and then reuse this variable. At least within the bounds of a single method, like here.

2025-03-07 11:56 UTC, AnnaShaleva commented on src/Neo/ProtocolSettings.cs
> +        /// The milliseconds between two block in NEO.
```suggestion
        /// The milliseconds between two blocks in Neo.
```

2025-03-07 11:56 UTC, AnnaShaleva commented on src/Neo/ProtocolSettings.cs
> +        /// For code that needs the accurate block generation time based on blockchain state,
And I won't call it accurate, because Policy's value can be much different from config's value. So just tell that this field should be considered as deprecated after Echidna.

2025-03-07 11:56 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            if (item is null) return DefaultBlockGenTime;
It can't be null, we initialize this value at Echidna's start height. Just use
```
 return (uint)(BigInteger)snapshot[_blockGenTime];
```

2025-03-07 11:56 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            engine.SendNotification(Hash, "BlockGenTimeChanged",
This notification must be declared in the Policy's manifest starting from Echidna, otherwise it's illegal to emit this notification.

2025-03-08 09:56 UTC, vncoelho commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +            catch (System.Collections.Generic.KeyNotFoundException)
I prefer an explicit if to meet that condition

2025-03-09 21:26 UTC, vncoelho commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                if (!system.Settings.IsHardforkEnabled(Hardfork.HF_Echidna, index - 1))
I think that this kind of code should becleaned after the HardFork is enabled.

2025-03-10 06:15 UTC, superboyiii commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            if (item is null) return DefaultBlockGenTime;
> It can't be null, we initialize this value at Echidna's start height. Just use
> 
> ```
>  return (uint)(BigInteger)snapshot[_blockGenTime];
> ```

It won't be null. It's declared at the begining.

2025-03-10 06:20 UTC, Jim8y commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(DefaultBlockGenTime));
this is policy contract, it can not read from the config.

2025-03-10 06:32 UTC, Jim8y commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                return TimeSpan.FromMilliseconds(milliseconds);
but the execution of contract are after consensus, which means if height 1000 enables we can read the value at height 1001. 

this change is different from all other hardfork change cause previously all changes take effect at block runtime, while this change take effect at the consensus time, which is before the block runtime.

2025-03-10 06:39 UTC, Jim8y commented on src/Neo/ProtocolSettings.cs
> +        /// For code that needs the accurate block generation time based on blockchain state,
```suggestion
        /// For code that needs the block generation time based on blockchain state, 
```

2025-03-10 06:41 UTC, Jim8y commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            if (item is null) return DefaultBlockGenTime;
can be a future optimization?

2025-03-10 11:16 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            if (item is null) return DefaultBlockGenTime;
No, just update the code.

2025-03-10 11:19 UTC, Jim8y commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            if (item is null) return DefaultBlockGenTime;
any particular reason of must update now?

2025-03-10 16:52 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(DefaultBlockGenTime));
See https://github.com/nspcc-dev/neo-go/pull/3835 for the reference, please. In particular, we need this:
https://github.com/nspcc-dev/neo-go/blob/e615a90c24c761e3f176b4fa87aad0d14662c37e/pkg/core/native/policy.go#L214-L215

2025-03-10 16:52 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            if (item is null) return DefaultBlockGenTime;
We need to follow the behaviour of other system settings setters (like `GetStoragePrice`, `GetExecFeeFactor` and `GetFeePerByte`.  The value of `blockGenTime` must be stored in the Policy storage during Echidna-level contract initialization. If (for some reason) this value is missing from the storage then it's a bug in the Policy contract and we need to fix this bug instead of returning default value.

2025-03-13 07:55 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 1000;
Let's use `0` as a minimum bound and `30_000` as the maximum bound. Ref. https://github.com/nspcc-dev/neo-go/pull/3835#discussion_r1991406720

2025-03-13 07:55 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public uint GetBlockGenTime(IReadOnlyStore snapshot)
I'd also propose to rename it to `MSPerBlock` or `MillisecondsPerBlock`, the reason is in https://github.com/nspcc-dev/neo-go/pull/3835#discussion_r1991409587.

2025-03-17 08:08 UTC, vncoelho commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                if (!settings.IsHardforkEnabled(Hardfork.HF_Echidna, index))
After the hardfork is implemented I think we should remove this and set a default 15s on the storage itself.

2025-03-17 08:11 UTC, vncoelho commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 1000;
This `MinBlockGenTime = 1000;` will be bad for privatenet tests and benchamarks,

Set this to 100

2025-03-17 08:12 UTC, vncoelho commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                if (!settings.IsHardforkEnabled(Hardfork.HF_Echidna, index))
It is ok like this for now anyway

2025-03-25 16:17 UTC, AnnaShaleva reviewed
Let's resume our work on this PR, we need to move on with these changes.

2025-03-25 16:17 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
>          /// Gets the fee for attribute before Echidna hardfork.
Useless change, revert it.

2025-03-25 16:17 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
One thing that I'm not sure about is that this initial value `engine.ProtocolSettings.MillisecondsPerBlock` is not moved to a separate config section. I'm not sure we need it, but I implemented it on the NeoGo side (a separate field in `GenesisConfiguration` section, see the https://github.com/nspcc-dev/neo-go/pull/3835).

It's not critical and we may keep it as is in the C# implementation, but I'd like to hear @roman-khimov's opinion.

2025-03-25 16:17 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 1000;
This check is already added to `SetMSPerBlock` method.

So now `MinBlockGenTime` constant should be removed since it's unused.

2025-03-25 16:17 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +            TimeSpan blockTime = GetBlockGenTime();
One thing that should be changed regarding consensus part: it's better to bind `blockTime` to the consensus context, because this value can not be changed within the block processing frame. Check how it implemented in https://github.com/nspcc-dev/dbft/pull/147, in particular, https://github.com/nspcc-dev/dbft/blob/b5dd36eb90f791efdf137069d2a8197145ef92ca/context.go#L250.

So we initialize the context-bound `blockTime` at view 0, and then reuse it from every other handler until next block is accepted. It's needed because these repetitive calls to Policy state (`GetBlockGenTime()`) are useless.

2025-03-25 16:28 UTC, roman-khimov commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
Configs are implementation-specific, I'd recommend a dedicated "Genesis" section in the "ProtocolConfiguration", but it's just a recommendation.

2025-03-31 09:33 UTC, AnnaShaleva reviewed
Policy part is OK to me, but consensus part still should be adjusted.

2025-03-31 09:33 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 100;
```suggestion
        public const uint MinBlockGenTime = 0;
```

It was like this in the last version of this PR, but the latest commit changed it.

2025-03-31 09:33 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        /// <param name="milliseconds">The block generation time in milliseconds. Must be between MinBlockGenTime and DefaultBlockGenTime.</param>
```suggestion
        /// <param name="milliseconds">The block generation time in milliseconds. Must be between MinBlockGenTime and MaxBlockGenTime.</param>
```

2025-03-31 09:33 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +
Revert these changes, they are not a part of this PR. This PR must only contain the logic that moves dBFT from ProtocolConfig-based MSPerBlock to Policy-based value.

2025-03-31 09:33 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
Ditto, we need a separate PR for these changes.

2025-03-31 09:33 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
You need to initialize it even on watch-only nodes, move this line before `if (context.WatchOnly) return;`.

2025-03-31 09:33 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
You need to initialize it only at view 0, because block time can't be updated between views.

2025-03-31 09:36 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
> +
It was originally a part of https://github.com/neo-project/neo/pull/3637, so let's keep this logic there.

2025-03-31 12:15 UTC, Jim8y commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
> You need to initialize it only at view 0, because block time can't be updated between views.

This does not matter, pelase focus on logic, optimization can be done at any time. As long as the logic is right, should be fine.

2025-03-31 12:16 UTC, Jim8y commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 100;
Why the min is 0 ? is not it 100 in our last meeting?

2025-03-31 12:22 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
It's not an optimisation, it's the logic issue, and it needs to be fixed. The node may get some new block from the network, and it's just not correct to retrieve the updated block generation time if the node is trying to change its view at this moment. In this situation new block generation time should be applied only starting from the next height, when consensus is initialized at view 0.

2025-03-31 12:28 UTC, Jim8y commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
This does not matter, has being evaluated in real testnet and passed stress test, this pr has being there for too long,  will have another solid test and run, and most importantly this is not a protocol levele change, so please allow me to keep it.

2025-03-31 12:31 UTC, Jim8y commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
Would you mind to have a brand new pr to replace mine, i think i am lost here and is not able to follow your directions. Would definatly be much easier and faster if you could do it directly.

2025-03-31 12:34 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
It matters since it's a separate logic change that affects the consensus behaviour and that is not related to 3 seconds consensus in any way. It should be reviewed carefully and we'd better so it in a separate PR.

@roman-khimov

2025-03-31 12:37 UTC, Jim8y commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
> It matters since it's a separate logic change that affects the consensus behaviour and that is not related to 3 seconds consensus in any way. It should be reviewed carefully and we'd better so it in a separate PR.
> 
> @roman-khimov

That is realated, 3 seconds will cause higher delay, this change is for solving that issue and make the consensus more stable and mitigate the delay impact.

2025-03-31 12:38 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
Just move `blockGenTime = neoSystem.GetBlockGenTime()` to `context.Reset` function under `if (viewNumber == 0)` condition, that's it.

2025-03-31 12:39 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
https://github.com/neo-project/neo/pull/3622#discussion_r2020964623 will solve the problem.

2025-03-31 12:47 UTC, roman-khimov commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
This particular change could've been merged months ago, it's pretty clear on its own and tested well enough now. But for whatever reason it's sitting here with a number of Policy changes that we're trying to settle. An option too, just some overhead for everyone involved.

2025-04-01 01:45 UTC, vncoelho reviewed
There are some minor changes since I reviewed, why them? Please check my comments

2025-04-01 01:45 UTC, vncoelho commented on docs/config.json.md
>  - **MillisecondsPerBlock**: Time interval between blocks in milliseconds. Default is `15000` (15 seconds).
Still this will be the easiest way for private nets otherwise we will need a round of multi sig decision.

So, better to explain that this is still configurable

2025-04-01 01:45 UTC, vncoelho commented on src/Neo/Ledger/Blockchain.cs
> +                TimeSpan blockGenTime = system.GetBlockGenTime();
Why this? I do not thing it is necessary and quite strange.

2025-04-01 13:28 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +        public const uint MinBlockGenTime = 100;
No. As mentioned in https://github.com/neo-project/neo/pull/3622#discussion_r1984840756, 100 is not enough for us.

2025-04-01 21:37 UTC, cschuchardt88 approved these changes

2025-04-02 13:27 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
Solved in [f167925](https://github.com/neo-project/neo/pull/3622/commits/f1679256226ee98a7e2476b7ec3bab23b3693270).

2025-04-02 13:27 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +            blockGenTime = neoSystem.GetBlockGenTime();
Implemented in [f167925](https://github.com/neo-project/neo/pull/3622/commits/f1679256226ee98a7e2476b7ec3bab23b3693270).

2025-04-02 13:28 UTC, AnnaShaleva commented on src/Neo/Ledger/Blockchain.cs
> +                TimeSpan blockGenTime = system.GetBlockGenTime();
See https://github.com/neo-project/neo/pull/3622#discussion_r2020689634, this logic was originally ported from #3637.

2025-04-02 14:59 UTC, AnnaShaleva approved these changes
I've updated the consensus logic, you can check the last several commits. Just for the record: now consensus update includes both Policy changes and improvement of block generation time (https://github.com/neo-project/neo/pull/3637), see https://github.com/neo-project/neo/pull/3622#discussion_r2020689634.

So @neo-project/core let's review one more time at least the code part, because we need to move on with these changes.

I didn't touch the `NEP-BlockTimeGASRate.md` part since I don't quite like it, it contains a lot of C#-specific implementation details whereas it's declared to be a NEP, and all NEPs are supposed to be implementation-agnostic. But this documentation file has some inaccuracies (e.g. minimal block gen time value is outdated).

2025-04-03 10:04 UTC, Jim8y commented
> I didn't touch the `NEP-BlockTimeGASRate.md` part since I don't quite like it, it contains a lot of C#-specific implementation details whereas it's declared to be a NEP, and all NEPs are supposed to be implementation-agnostic. But this documentation file has some inaccuracies (e.g. minimal block gen time value is outdated), so @Jim8y feel free to update it.

This is in the C# code and is of course a c# implementation documentation  and is not an NEP. The NEP that i want to have on 3s is under the proposal repo. If the name is misleading of course we can remove it, change its name, or whatever that can make people feels better.

2025-04-10 06:15 UTC, shargon commented
@Jim8y Conflicts, I need more tests..

2025-04-10 09:23 UTC, Jim8y commented
> > @Jim8y Conflicts, I need more tests..
> 
> @shargon, it looks like I'm the maintainer of this PR now, so conflicts are fixed, please take a look one more time. I'll add a unit test for Policy changes later. @vncoelho, we also need your review.
> 
> > This is in the C# code and is of course a c# implementation documentation and is not an NEP. The NEP that i want to have on 3s is under the proposal repo. If the name is misleading
> 
> @Jim8y, regarding this NEP: it's not only about the name is misleading, it's more about the fact that content of this file diverges from the current implementation. Since you haven't pushed any fixes, I removed this file from the current PR in order not to delay 3-s consensus changes. Later, when you have time, you may create a separate PR to update the documentation part, and we'll review it.

Let me remove the document first, then add another version after the release of v3.8

2025-04-10 09:49 UTC, AnnaShaleva commented on src/Plugins/StateService/Verification/VerificationService.cs
> +        private static readonly uint TimeoutMilliseconds = (uint)StatePlugin._system.GetBlockGenTime().TotalMilliseconds;
Good catch, fixed, see the latest commit.

2025-04-10 09:50 UTC, AnnaShaleva commented
> I'll add a unit test

Added.

2025-04-10 10:19 UTC, shargon commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
Technically a cn with 16 sec can work with a cn with 15 sec, so maybe we can have a state difference if the node is not well configured

2025-04-10 10:21 UTC, vncoelho commented
> > @Jim8y Conflicts, I need more tests..
> 
> @shargon, it looks like I'm the maintainer of this PR now, so conflicts are fixed, please take a look one more time. I'll add a unit test for Policy changes later. @vncoelho, we also need your review.
> 
> > This is in the C# code and is of course a c# implementation documentation and is not an NEP. The NEP that i want to have on 3s is under the proposal repo. If the name is misleading
> 
> @Jim8y, regarding this NEP: it's not only about the name is misleading, it's more about the fact that content of this file diverges from the current implementation. Since you haven't pushed any fixes, I removed this file from the current PR in order not to delay 3-s consensus changes. Later, when you have time, you may create a separate PR to update the documentation part, and we'll review it.

Sure, give me until tomorrow

2025-04-10 10:23 UTC, shargon commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
It's better to avoid the default value, and take it from settings if is not present, then we can ensure this strange and specific case

2025-04-10 10:24 UTC, shargon commented
https://github.com/neo-project/neo/pull/3622/files#r2037019862 (conversion is collapsed)

2025-04-10 10:36 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
> Technically a cn with 16 sec can work with a cn with 15 sec

And it looks to me that in this case the "faulty" node should fix its configuration, remove its state and sync from genesis with proper configuration.

2025-04-10 11:15 UTC, shargon commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
I mean, avoid write the default value on genesis, and fault if is not present, we already have a method to avoid call this if is not in hf

2025-04-10 11:30 UTC, vncoelho commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                return TimeSpan.FromMilliseconds(settings.MillisecondsPerBlock);
When is the key added to the storage? I am thinking about when we set HF_Echidna to 0, then we may have problems

2025-04-10 11:31 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
> I mean, avoid write the default value on genesis

But it won't be written to genesis block; it will be written to the block of Echidna activation. And we need the initial value to be a part of the node's state, so that all nodes can rely on this state-based value right after Echidna fork.

2025-04-10 11:35 UTC, vncoelho commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
if we write the default value on genesis we will have state difference for mainnet.

But what I did not understand completely is when we set HF to index 0 on a privatenet, if it will keep getting the default even without consensus calling the method.

2025-04-10 11:35 UTC, AnnaShaleva commented on src/Neo/Extensions/NeoSystemExtensions.cs
> +                return TimeSpan.FromMilliseconds(settings.MillisecondsPerBlock);
> When is the key added to the storage? 

At the block of HF_Echidna activation.

> I am thinking about when we set HF_Echidna to 0, then we may have problems

Why? I'll check it on privnet, but in general I don't think there will be any problem, because this value is available right after genesis block's OnPersist trigger is processed (if we're talking about `HF_Echidna: 0` setting).

2025-04-10 11:41 UTC, vncoelho commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
I missed this line, me previous comments are solved. Sorry for that.

2025-04-10 11:43 UTC, vncoelho commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
My mistake, the way it is here is correct.

2025-04-10 11:52 UTC, vncoelho approved these changes

2025-04-10 14:16 UTC, shargon commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
> > I mean, avoid write the default value on genesis
> 
> But it won't be written to genesis block; it will be written to the block of Echidna activation. And we need the initial value to be a part of the node's state, so that all nodes can rely on this state-based value right after Echidna fork.

How do you will trust on it if during echina my cn write 16 and you 15?

2025-04-10 14:26 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
> How do you will trust on it if during echina my cn write 16 and you 15?

We're using dBFT, so the dBFT assumption about the number of "correct" nodes in the network works here. At least `M` out of `N` CNs should have valid configurations and hence, valid states.

2025-04-10 14:44 UTC, vncoelho commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
> > > I mean, avoid write the default value on genesis
> > 
> > But it won't be written to genesis block; it will be written to the block of Echidna activation. And we need the initial value to be a part of the node's state, so that all nodes can rely on this state-based value right after Echidna fork.
> 
> How do you will trust on it if during echina my cn write 16 and you 15?

I understand your concern, but it is like Anna highlighted.
2f+1 should have config correct.

In addition, it will lead to state difference,right?

I think that we should follow her advise as well to move this parameter from config.json to genesis.json

2025-04-10 17:58 UTC, shargon commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
> > How do you will trust on it if during echina my cn write 16 and you 15?
> 
> We're using dBFT, so the dBFT assumption about the number of "correct" nodes in the network works here. At least `M` out of `N` CNs should have valid configurations and hence, valid states.

But if one of these nodes have a different time per block, can work well and write a different value in the storage in the initialization, because this value was not agree by them, it's in the config of everyone

2025-04-10 18:37 UTC, roman-khimov commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +                engine.SnapshotCache.Add(_blockGenTime, new StorageItem(engine.ProtocolSettings.MillisecondsPerBlock));
It's a buggy node then. Not much different from invalid standby validator set or invalid HF height. A node with invalid HF height is likely to work, but it's also likely to have a different state. Genesis of HF-dependent values should be synchronized on all nodes.

2025-04-10 19:05 UTC, shargon commented on src/Neo/ProtocolSettings.cs
>          public uint MillisecondsPerBlock { get; init; }
We can use obsolete to avoid the use, only in the new method

2025-04-10 19:06 UTC, shargon commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            snapshot.TryGet(_blockGenTime, out var item);
If ! throw an exception instead of get null exception should be good for debug

2025-04-10 19:08 UTC, shargon commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.Check.cs
>                  Block block = context.CreateBlock();
What's happend with this variable?

2025-04-10 19:09 UTC, shargon commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
Extra condition?

2025-04-10 19:10 UTC, shargon commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
Two prs is better, easier to review and don't miss anything

2025-04-11 02:34 UTC, vncoelho commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
I did not notice that! Good eyes @shargon.

I will dismiss my approval until this is clarified.

2025-04-11 05:40 UTC, cschuchardt88 approved these changes

2025-04-11 10:14 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
Yes, extra condition, because @Jim8y wants to include https://github.com/neo-project/neo/pull/3637 into this PR. So this PR contains not only MSPerBlock Policy extension, but also dBFT improvement (#3627), that's why I asked review from @vncoelho.

2025-04-11 10:15 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.Check.cs
>                  Block block = context.CreateBlock();
It's removed because it's not used after we implement https://github.com/neo-project/neo/pull/3622#discussion_r2039247568.

2025-04-11 10:16 UTC, AnnaShaleva commented on src/Neo/ProtocolSettings.cs
>          public uint MillisecondsPerBlock { get; init; }
But this value is actually not obsolete, it's still used until Echidna is enabled. And it's used to initialize Policy at Echidna height, so this value will never be removed from the node's configuration.

2025-04-11 10:18 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            snapshot.TryGet(_blockGenTime, out var item);
We should just use simple index expression here, like for any other Policy getter method. Will fix.

2025-04-11 10:20 UTC, AnnaShaleva commented on src/Neo/SmartContract/Native/PolicyContract.cs
> +            snapshot.TryGet(_blockGenTime, out var item);
Fixed.

2025-04-11 10:26 UTC, cschuchardt88 approved these changes
LGTM

2025-04-11 10:30 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
If you wish, I can split this PR into two PRs to decouple Policy update from dBFT timer logic change. That was my original intention in https://github.com/neo-project/neo/pull/3622#discussion_r2020688801.

2025-04-11 10:32 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
OK, I see https://github.com/neo-project/neo/pull/3622#discussion_r2038123407, let's use two separate PRs.

2025-04-11 11:58 UTC, vncoelho commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
@AnnaShaleva, in fact I knew about the change in how to process block time.

Initially I was against changing it here directly because it is off course not the focus of this PR, but @Jim8y insisted and said @superboyiii was testing on testnet for long time.
So, we did also our experiments with this PR and the behaviours was quite good, we introduced adversaries delays, blocked communication and etc...The results were better than before.

But, when I say better than before, I mean the overall neo-core itself, not the change separately.
In this sense, I still believe it should be merged in another PR, let's say a minor patch after release. That is my opinion.

Finally, this specially line changed we are discussing here I did not pay attention before. I will check it carefully know to understand if it is related to the change in the definition of the relative block time.

2025-04-11 11:59 UTC, AnnaShaleva commented
As agreed in https://github.com/neo-project/neo/pull/3622#discussion_r2039274156, this PR will be replaced by two PRs to split the logic: native Policy update (https://github.com/neo-project/neo/pull/3895) and dBFT timer adjustment (will create it after the merge of #3895).

2025-04-11 11:59 UTC, closed without merging

2025-04-11 12:01 UTC, vncoelho approved these changes

2025-04-11 15:53 UTC, AnnaShaleva commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
Let's use #3895, it's more clean and contains a single logical change, it's easier to review for everyone.