[Core Plugin DBFT] include consensus time into block interval
neo-project/neo pull request #3637
Opened 2024-12-20 00:09 UTC by Jim8y

# Description

this pr implements issue https://github.com/neo-project/neo/issues/3627 to include consensus time into block interval. 

Fixes # [(issue)](https://github.com/neo-project/neo/issues/3627)

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-20 10:21 UTC, shargon reviewed
Just to know

2024-12-20 10:21 UTC, shargon commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
This is required? seems a fix for a different thing

2024-12-20 12:20 UTC, vncoelho requested changes
From my perspective this change is not essential right at this moment.

I am not against the idea of the change itself, but I am not in favor of merging this without strong tests, as we already did in the past.
This requires a setup with delay and a design of experiments that simulate mainnet.
Otherwise, setup some nodes on cloud and test it.

2024-12-20 12:20 UTC, vncoelho commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                        var diff = TimeProvider.Current.UtcNow - onPrepareReceivedTime;
I believe this methodology can trigger strange behaviors in a real scenario, after change views, delays and etc...

2024-12-20 12:31 UTC, vncoelho commented
My suggestion is that each core dev interested in the PR should setup a node.

I am available for that. Just set a date and my node will be ready to join our Core Testnet.
We can share any needed details internally to make a quick setup.

2024-12-20 12:41 UTC, Jim8y commented
> From my perspective this change is not essential right at this moment.
> 
> I am not against the idea of the change itself, but I am not in favor of merging this without strong tests, as we already did in the past.
> This requires a setup with delay and a design of experiments that simulate mainnet.
> Otherwise, setup some nodes on cloud and test it.

Tests will be done only after this one is properly reviewed, otherwise if this pr keeps changing, it's meaningless to carry out any real world tests.

2024-12-31 09:15 UTC, roman-khimov reviewed
See https://github.com/nspcc-dev/dbft/pull/56#issuecomment-2566268782 for my results, in general the approach is good and it can be done for the good.

Just don't expect this to give you <5% deviations on 3s mainnet, it's good, but not sufficient for that purpose.

2024-12-31 09:15 UTC, roman-khimov commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> -                        var diff = TimeProvider.Current.UtcNow - block_received_time;
Likely `block_received_time` is not needed now.

2025-02-13 14:12 UTC, roman-khimov approved these changes

2025-02-13 14:12 UTC, roman-khimov commented on src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
> +                    if (block_received_index + 1 == context.Block.Index && onPrepareBlockIndex + 1 == context.Block.Index)
It's required. In fact, it was also required previously, because node can miss PrepareRequest from the previous round and get a block via P2P in which case using the `onPrepareReceivedTime` would be wrong.

2025-03-28 09:54 UTC, Jim8y commented
close as can be done in another pr

2025-03-28 09:59 UTC, closed without merging